---
name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install yamllint
        run: sudo apt install -y --no-install-recommends yamllint
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
